### ISSUE TITLE
[Bytes] Format and Parse are not always reversible

### ISSUE THREAD

**Issue by mdouchement** [labstack/gommon#12]
### Description

Parse function does not support float values.

### Expected behaviour

Support float values.

```go
str := bytes.Format(13231323)
// -> 12.62MB

b, err := bytes.Parse(str)
// b -> 13233029  (truncated float 13233029.12)
// err ->  nil
```

### Actual behaviour

```go
str := bytes.Format(13231323)
// str -> 12.62MB

_, err := bytes.Parse(str)
// err ->  error parsing value=12.62MB
```

### Version/commit

`f72d3c883f8ea180da8f085dd320804c41332ad1`

**Comment by im-kulikov** [comment]
Fixed by - https://github.com/labstack/gommon/pull/16
