### ISSUE TITLE
Redirect stdout affects stderr

### ISSUE THREAD

**Issue by suntong** [labstack/gommon#15]
Should redirecting stdout affect stderr? 

Please take a look at this [simple Color.go](https://github.com/suntong/lang/blob/master/lang/Go/src/sys/Color.go)

The last two lines are from os.Stderr, and they will loose color when redirecting stdout:

![image](https://user-images.githubusercontent.com/422244/34457753-c574893c-ed88-11e7-8bdb-cc4c8ef58d4c.png)

Is it controlled by the OS or by the `color` package? 

Thx!

**Comment by suntong** [comment]
Confirmed that is cause by color package. 

```
 go run Color.go > /tmp/t
 cat /tmp/t
 echo abc def ghi | grep --color=always def | tee /tmp/t2
 cat /tmp/t2
```

Only the color package cause loosing the color. `grep --color=always` will keep it.

**Comment by im-kulikov** [comment]
```go

	color.SetOutput(os.Stderr)
	color.Enable()
	color.Println(color.Black("black"),
		color.Red("red"),
		color.Green("green"),
		color.Yellow("yellow"),
		color.Blue("blue"),
		color.Magenta("magenta"),
		color.Cyan("cyan"),
		color.White("white"),
		color.Grey("grey"))
```

Works fine

**Comment by suntong** [comment]
- Is my above [simple Color.go](https://github.com/suntong/lang/blob/master/lang/Go/src/sys/Color.go) works fine for you as well? 
- did you test the case when not redirecting stdout? 

I.e., I don't think any one would do `color.SetOutput(os.Stderr)` in their normal program.

**Comment by im-kulikov** [comment]
@suntong see example 2 and 3

**Comment by suntong** [comment]
Oh, got you. THX!

**Comment by im-kulikov** [comment]
@suntong no problem, you're welcome 😉
