### ISSUE TITLE
Provide another format/parse for bytes

### ISSUE THREAD

**Issue by ferhatelmas** [labstack/gommon#22]
Is it possible to support SI (power of 1000s, instead of 1024s) with a flag ?

```
690000 -> 673.83KB
690000 -> 690KB
```

**Comment by Cansuisak** [comment]
Excuse me if I'm not understanding the question correctly but the only comment I can make here is that with the tenders, the exact number written in the CSV should be submitted. (Maybe above comment was not even addressed to me)

**Comment by vishr** [comment]
Not with the current implementation. I am open for a PR.

**Comment by aldas** [comment]
closing, done with #45
