### ISSUE TITLE
bytes package is not ISO/IEC 80000 and IEEE 1541 complient

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [labstack/gommon#28]
according to Clause 4 of the [ISO/IEC 80000](https://github.com/labstack/gommon/issues/28#issue-392304417) standard and [IEEE 1541](https://en.wikipedia.org/wiki/IEEE_1541-2002)
among other things, the SI prefixes strictly refer to powers of ten and should not be used to indicate binary multiples

instead the Ki,Mi,Gi,.. prefixes should be used to indicate power of 2s

more on: https://en.wikipedia.org/wiki/Binary_prefix#IEC_prefixes

proposed solution:
change the current units from Si prefixes to Binary prefixes (KB->KiB,MB->MiB,GB->GiB,..) 
and then (optionally) add support for Si units

**Comment by vishr** [comment]
@Kallinteris-Andreas I am open for a PR
