### ISSUE TITLE
module requires Go 1.13

### ISSUE THREAD

**Issue by xponrails** [labstack/gommon#36]
Hi, I've update echo to v4 and after a go get command I receive:

go build github.com/labstack/gommon/random: module requires Go 1.13
go build github.com/labstack/gommon/color: module requires Go 1.13
go build github.com/labstack/gommon/bytes: module requires Go 1.13

My go version is 1.11 that is supported by Echo v4.

Why this package requires v 1.13?

**Comment by sunlianqiang** [comment]
change version from 0.2.9 to 0.2.8 can  fix the bug

**Comment by vishr** [comment]
This has been fixed in latest of echo & gommon.
